routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::middleware(['auth'])->group(
    function () {
        Route::prefix('admin')->group(
            function () {
                Route::get('/', 'AdminController@index')->name('admin.home');
                Route::resource('bookings', 'AdminBookingController');
                Route::resource('feedback', 'AdminFeedbackController');

                Route::prefix('booking')->group(
                    function () {
                        Route::get('/step_one', 'AdminBookingController@selectDay')->name('admin.create.day');
                        Route::post('/step_one', 'AdminBookingController@selectDayPost')->name('admin.create.dayPost');
                        Route::get('/step_two', 'AdminBookingController@selectTime')->name('admin.create.time');
                        Route::post('/step_two', 'AdminBookingController@selectTimePost')->name(
                            'admin.create.timePost'
                        );
                        Route::get('/step_info', 'AdminBookingController@info')->name('admin.create.info');

                        Route::prefix('edit')->group(
                            function () {
                                Route::get('/{booking}/step_one', 'AdminBookingController@editDay')->name(
                                    'admin.edit.day'
                                );
                                Route::post('/{booking}/step_one', 'AdminBookingController@editDayPost')->name(
                                    'admin.edit.dayPost'
                                );
                                Route::get('/{booking}/step_two', 'AdminBookingController@editTime')->name(
                                    'admin.edit.time'
                                );
                                Route::post('/{booking}/step_two', 'AdminBookingController@editTimePost')->name(
                                    'admin.edit.timePost'
                                );
                                Route::get('/{booking}/step_info', 'AdminBookingController@editInfo')->name(
                                    'admin.edit.info'
                                );
                            }
                        );
                    }
                );
            }
        );
    }
);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact_us', 'ContactController@index')->name('contact');
Route::post('/contact_us', 'ContactController@store')->name('contact.store');

Route::prefix('booking')->group(
    function () {
        Route::get('/step_one', 'BookingController@selectDay')->name('booking.day');
        Route::post('/step_one', 'BookingController@selectDayPost')->name('booking.dayPost');
        Route::get('/step_two', 'BookingController@selectTime')->name('booking.time');
        Route::post('/step_two', 'BookingController@selectTimePost')->name('booking.timePost');
        Route::get('/step_info', 'BookingController@info')->name('booking.info');
        Route::post('/booking', 'BookingController@store')->name('booking.store');
    }
);

app/Http/Controllers/AdminBookingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreBooking;
use App\Http\Requests\StoreDateBooking;
use App\Http\Requests\StoreTimeBooking;
use App\Http\Requests\UpdateBooking;
use App\Services\BookingService;
use App\Services\ClientService;
use App\Models\Booking;

class AdminBookingController extends Controller
{

    public function __construct(BookingService $booking, ClientService $client)
    {
        $this->booking = $booking;
        $this->client = $client;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin_booking.index', ['bookings' => $this->booking->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function selectDay()
    {
        $disabledDays = $this->booking->disabledDays();
        return view('admin_booking.create-step1', ['disabledDays' => $disabledDays]);
    }

    public function selectDayPost(StoreDateBooking $request)
    {
        $freeTime = $this->booking->freeTime($request->booking_date);
        $request->session()->put(['booking_date' => $request->booking_date]);
        $request->session()->put(['free_time' => $freeTime]);
        return redirect()->route('admin.create.time');
    }

    public function selectTime()
    {
        if (empty(session('booking_date'))) {
            return redirect()->route('admin.create.day');
        }
        return view(
            'admin_booking.create-step2',
            [
                'freeTime' => session('free_time'),
                'bookingDate' => session('booking_date')
            ]
        );
    }

    public function selectTimePost(StoreTimeBooking $request)
    {
        $request->session()->put(['booking_time' => $request->booking_time]);
        return redirect()->route('admin.create.info');
    }

    public function info()
    {
        if (empty(session('booking_date'))) {
            return redirect()->route('admin.create.day');
        } elseif (empty(session('booking_time'))) {
            return redirect()->route('admin.create.time');
        }
        return view(
            'admin_booking.create-info',
            ['bookingTime' => session('booking_time'), 'bookingDate' => session('booking_date')]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreBooking $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBooking $request)
    {
        $client = $this->client->create($request->all());
        $booking = $this->booking->create(
            [
                "client_id" => $client->id,
                "reserved_time" => $request->session()->get('booking_time'),
                "date" => $request->session()->get('booking_date')
            ]
        );
        $request->session()->forget(['booking_date', 'booking_time', 'free_time']);
        return redirect()->route("bookings.index");
    }

    /**
     * Display the specified resource.
     *
     * @param Booking $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking)
    {
        return view('admin_booking.show', ["booking" => $booking]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return
     */
    public function editDay(Booking $booking)
    {
        $disabledDays = $this->booking->disabledDays();
        return view('admin_booking.edit-step1', ['booking' => $booking, 'disabledDays' => $disabledDays]);
    }

    public function editDayPost(StoreDateBooking $request, Booking $booking)
    {
        $freeTime = $this->booking->freeTime($request->booking_date);
        $request->session()->put(['booking_date' => $request->booking_date]);
        $request->session()->put(['free_time' => $freeTime]);
        return redirect()->route('admin.edit.time', ['booking' => $booking]);
    }

    public function editTime(Booking $booking)
    {
        return view(
            'admin_booking.edit-step2',
            [
                'booking' => $booking,
                'freeTime' => session('free_time'),
                'bookingDate' => session('booking_date')
            ]
        );
    }

    public function editTimePost(StoreTimeBooking $request, Booking $booking)
    {
        $request->session()->put(['booking_time' => $request->booking_time]);
        return redirect()->route('admin.edit.info', ['booking' => $booking]);
    }

    public function editInfo(Booking $booking)
    {
        return view(
            'admin_booking.edit-info',
            [
                'booking' => $booking,
                'bookingTime' => session('booking_time'),
                'bookingDate' => session('booking_date')
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateBooking $request
     * @param int $id
     * @return //\Illuminate\Http\Response
     */
    public function update(UpdateBooking $request, Booking $booking)
    {
        $this->booking->update(
            $booking->id,
            [
                "reserved_time" => $request->session()->get('booking_time'),
                "date" => $request->session()->get('booking_date')
            ]
        );
        $this->client->update($booking->client_id, $request->all());


        return redirect()->route('bookings.show', ['booking' => $booking]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking)
    {
        $this->client->destroy($booking->client_id);
        $this->booking->destroy($booking->id);
        return redirect()->route('bookings.index');
    }


}

resources/views/admin_booking/create-info.blade.php
@extends('adminlte::page')
@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
@stop


@section('content_header')
    <div class="container">
        <h1 class="m-0 ml-5 text-dark">Create Booking - Step 3 - Info</h1>
    </div>
@stop

@section('content')
    <div class="container">
        <form method="POST" action="{{route('bookings.store')}}">
            @csrf
            <div class="card-body">
                <!--   Choice -->
                <div class="row form-group justify-content-center mb-3">
                    <div class="col-md-6">
                        <h4>The day of the booking</h4>
                    </div>
                    <div class="col-md-6">
                        <p> {{ $bookingDate }}</p>
                    </div>
                </div>
                <div class="row form-group justify-content-center mb-4">
                    <div class="col-md-6">
                        <h4>The time of the booking</h4>
                    </div>
                    <div class="col-md-6">
                        <p> {{ $bookingTime }}</p>
                    </div>
                </div>
                <!--   Choice -->
                <div class="form-group">
                    <label for="exampleInputFname">First Name</label>
                    <input name="fname" type="text" value="{{ old('fname') }}"
                           class="form-control {{ $errors->has('fname') ? 'is-invalid' : '' }}" id="exampleInputFname"
                           placeholder="Enter first name">
                    @if($errors->has('fname'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('fname') }}</strong>
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="exampleInputLname">Last Name</label>
                    <input name="lname" type="text" value="{{ old('lname') }}"
                           class="form-control {{ $errors->has('lname') ? 'is-invalid' : '' }}" id="exampleInputLname"
                           placeholder="Enter last name">
                    @if($errors->has('lname'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('lname') }}</strong>
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="exampleInputPhone">Mobile phone</label>
                    <input name="phone" type="tel" value="{{ old('phone') }}"
                           class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" id="exampleInputPhone"
                           placeholder="Enter phone in format 380993765589">
                    @if($errors->has('phone'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('phone') }}</strong>
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail">Email</label>
                    <input name="email" type="email" value="{{ old('email') }}"
                           class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" id="exampleInputEmail"
                           placeholder="Enter email">
                    @if($errors->has('email'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('email') }}</strong>
                        </div>
                    @endif
                </div>

                <div class="form-group">
                    <label class="text-black" for="message">Message</label>
                    <textarea name="message" id="message"
                              class="form-control @error('message') is-invalid @enderror"
                              placeholder="Write your notes or questions here...">{{old('message')}}</textarea>
                    @if($errors->has('message'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('message') }}</strong>
                        </div>
                    @endif
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Create Booking</button>
                </div>
            </div>
        </form>
    </div>
@stop

resources/views/admin_booking/create-step1.blade.php
@extends('adminlte::page')
@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
@stop


@section('content_header')
    <div class="container">
        <h1 class="m-0 ml-5 text-dark">Create Booking - Step 1 - Date</h1>
    </div>
@stop

@section('content')
    <div class="container">
        <form method="POST" action="{{route('admin.create.dayPost')}}">
            @csrf
            <div class="card-body">
                <!-- Date -->
                <div class="row form-group">
                    <div class="col-md-6">
                        <h4>Choice date for booking</h4>
                    </div>
                    <div class="col-md-6">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                            </div>
                            <input type="text" name="booking_date" class="form-control float-right" id="reservation">
                        </div>
                    </div>
                </div>
                <!-- end Date -->
            </div>
            <!-- /.card-body -->
            <div class="card-footer" style="background-color: rgba(0,0,0,0);">
                <div class="text-right">
                    <button type="submit" class="btn btn-primary text-white">Go to time</button>
                </div>
            </div>
        </form>
    </div>
@stop

@section('js')
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

    <script type="text/javascript">
        var disabledArr = @json($disabledDays);
        var dateMin = new Date();
        dateMin.setDate(dateMin.getDate() + (dateMin.getHours() >= 17 ? 1 : 0));
        $(function () {
            $('input[name="booking_date"]').daterangepicker({
                locale: {
                    format: 'YYYY-MM-DD'
                },
                singleDatePicker: true,
                showDropdowns: true,
                minYear: '2020',
                minDate: dateMin,
                maxYear: parseInt(moment().format('YYYY'), 10),
                isInvalidDate: function (arg) {
                    console.log(arg);

                    // Prepare the date comparision
                    var thisMonth = arg._d.getMonth() + 1;   // Months are 0 based
                    if (thisMonth < 10) {
                        thisMonth = "0" + thisMonth; // Leading 0
                    }
                    var thisDate = arg._d.getDate();
                    if (thisDate < 10) {
                        thisDate = "0" + thisDate; // Leading 0
                    }
                    var thisYear = arg._d.getYear() + 1900;   // Years are 1900 based

                    var thisCompare = thisMonth + "/" + thisDate + "/" + thisYear;
                    console.log(thisCompare);

                    if ($.inArray(thisCompare, disabledArr) != -1) {
                        console.log("      ^--------- DATE FOUND HERE");
                        return true;
                    }
                },
            }, function (start, end, label) {
                var years = moment().diff(start, 'years');
            });
        });
    </script>
@stop

resources/views/admin_booking/create-step2.blade.php
@extends('adminlte::page')
@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
@stop


@section('content_header')
    <div class="container">
        <h1 class="m-0 ml-5 text-dark">Create Booking - Step 2 - Time</h1>
    </div>
@stop

@section('content')
    <div class="container">
        <form method="POST" action="{{route('admin.create.timePost')}}">
            @csrf
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <h5>The day of the booking</h5>
                    </div>
                    <div class="col-md-6">
                        <p> {{ $bookingDate }}</p>
                    </div>
                </div>
                <!-- Date -->
                <div class="row form-group ">
                    <div class="col-md-6">
                        <h5>Choice time for booking</h5>
                    </div>
                    <div class="col-md-6">

                        <select class="form-control px-2" name="booking_time" id="time">
                            @for($i=0; $i < count($freeTime); $i++)
                                <option value="{{ $freeTime[$i] }}">{{ $freeTime[$i] }}</option>
                            @endfor
                        </select>

                    </div>
                </div>
                <!-- end Date -->
            </div>
            <!-- /.card-body -->
            <div class="card-footer" style="background-color: rgba(0,0,0,0);">
                <div class="text-right">
                    <button type="submit" class="btn btn-primary text-white">Continue</button>
                </div>
            </div>
        </form>
    </div>
@stop

resources/views/admin_booking/edit-info.blade.php
@extends('adminlte::page')

@section('content_header')
    <div class="container">
        <h1 class="m-0 ml-5 text-dark">Edit Booking</h1>
    </div>
@stop

@section('content')
    <div class="container">
        <form method="POST" action="{{route('bookings.update', ['booking' => $booking->id])}}">
            @csrf
            @method('PUT')
            <div class="card-body">
                <!--   Choice -->
                <div class="row form-group justify-content-center mb-3">
                    <div class="col-md-6">
                        <h4>The day of the booking</h4>
                    </div>
                    <div class="col-md-6">
                        <p> {{ $bookingDate }}</p>
                    </div>
                </div>
                <div class="row form-group justify-content-center mb-4">
                    <div class="col-md-6">
                        <h4>The time of the booking</h4>
                    </div>
                    <div class="col-md-6">
                        <p> {{ $bookingTime }}</p>
                    </div>
                </div>
                <!--   Choice -->
                <div class="form-group">
                    <label for="exampleInputFname">First Name</label>
                    <input name="fname" type="text" value="{{ old('fname') ?? $booking->client->fname }}"
                           class="form-control {{ $errors->has('fname') ? 'is-invalid' : '' }}" id="exampleInputFname"
                           placeholder="Enter first name">
                    @if($errors->has('fname'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('fname') }}</strong>
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="exampleInputLname">Last Name</label>
                    <input name="lname" type="text" value="{{ old('lname') ?? $booking->client->lname }}"
                           class="form-control {{ $errors->has('lname') ? 'is-invalid' : '' }}" id="exampleInputLname"
                           placeholder="Enter last name">
                    @if($errors->has('lname'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('lname') }}</strong>
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="exampleInputPhone">Mobile phone</label>
                    <input name="phone" type="tel" value="{{ old('phone') ?? ltrim($booking->client->phone, '+') }}"
                           class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" id="exampleInputPhone"
                           placeholder="Enter phone in format 380993765589">
                    @if($errors->has('phone'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('phone') }}</strong>
                        </div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail">Email</label>
                    <input name="email" type="email" value="{{ old('email') ?? $booking->client->email}}"
                           class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" id="exampleInputEmail"
                           placeholder="Enter email">
                    @if($errors->has('email'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('email') }}</strong>
                        </div>
                    @endif
                </div>

                <div class="form-group">
                    <label class="text-black" for="message">Message</label>
                    <textarea name="message" id="message"
                              class="form-control @error('message') is-invalid @enderror"
                              placeholder="Write your notes or questions here...">{{old('message') ?? $booking->client->message}}</textarea>
                    @error('message')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <div class="text-right">
                    <a href="{{route('admin.edit.time', ['booking' => $booking->id] )}}" class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i> Back
                    </a>
                    <button type="submit" class="btn btn-primary">Edit Booking</button>
                </div>
            </div>
        </form>
    </div>

@stop

resources/views/admin_booking/edit-step2.blade.php
@extends('adminlte::page')

@section('content_header')
    <div class="container">
        <h1 class="m-0 ml-5 text-dark">Edit Booking - Step 2</h1>
    </div>
@stop

@section('content')
    <div class="container">
        <form method="POST" action="{{route('admin.edit.timePost', ['booking' => $booking->id])}}">
            @csrf
            <div class="card-body">

                <div class="row form-group">
                    <div class="col-md-6">
                        <h5>The old booking time:</h5>
                        <div class="col-md-6">
                            <p> {{ $booking->reserved_time }}</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h5>New booking date:</h5>
                        <div class="col-md-6">
                            <p> {{ $bookingDate }}</p>
                        </div>
                    </div>
                </div>
                <!-- Date -->
                <div class="row form-group ">
                    <div class="col-md-6">
                        <label class="text-black " for="time">Time</label><br>
                        <select class="form-control px-2" name="booking_time" id="time">
                            @for($i=0; $i < count($freeTime); $i++)
                                <option value="{{$freeTime[$i] }}">{{ $freeTime[$i] }}</option>
                            @endfor
                        </select>
                    </div>
                </div>
                <!-- end Date -->

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <div class="text-right">
                    <a href="{{route('admin.edit.day', ['booking' => $booking->id])}}" class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i> Back
                    </a>
                    <button type="submit" class="btn btn-primary">Edit Info</button>
                </div>
            </div>
        </form>
    </div>

@stop

resources/views/admin_booking/index.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1 class="m-0 ml-5 text-dark">List of Booking</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
            <h5 class="card-title float-right">DataTable by date and time of booking</h5>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12 col-md-6"></div>
                    <div class="col-sm-12 col-md-6"></div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" role="grid"
                               aria-describedby="example2_info">
                            <thead>
                            <tr role="row">
                                <th> #</th>
                                <th> Date</th>
                                <th> Time</th>
                                <th> FullName Client's</th>
                                <th> Number phone</th>
                                <th> Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($bookings as $booking)
                                <tr role="row" class="odd">
                                    <td>{{ $booking->id }}</td>
                                    <td>{{ $booking ->date }}</td>
                                    <td>{{ $booking->reserved_time }}</td>
                                    <td>{{ $booking->client->getFullNameAttribute() }}</td>
                                    <td>{{$booking->client->phone}}</td>
                                    <td>
                                        <div class="row justify-content-around">
                                            <a class="btn btn-primary btn-sm"
                                               href="{{route('bookings.show', ['booking' => $booking->id])}}">
                                                <i class="fas fa-folder">
                                                </i>
                                                View
                                            </a>
                                            <a class="btn btn-info btn-sm"
                                               href="{{route('admin.edit.day', ['booking' => $booking->id])}}">
                                                <i class="fas fa-pencil-alt">
                                                </i>
                                                Edit
                                            </a>
                                            <form action="{{route('bookings.destroy',  $booking->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm"><i
                                                        class="fas fa-trash">
                                                    </i>Delete
                                                </button>
                                            </form>
                                        </div>

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
@stop

@section('js')
    <script>
        $(function () {
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
@stop